name: qwixx_gamesheet
description: Digital Game Sheet for Qwixx

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.6.0+10

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  assets_audio_player: ^3.1.1
  wakelock_plus: ^1.2.8
  in_app_review: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/images/